name:   Dan Donahue
url: http://dandonahue.net
description:    Dan Donahue's blog

limit_posts:	0
pygments:	true

paginate:	5
paginate_path:	"page/:num"

excerpt_separator:      "\n\n"

markdown:	redcarpet
markdown_ext:	markdown,mkd,mkdn,md

